[CURA-9036] Fix using wrong junctions when calculating areas.
Ultimaker/CuraEngine pull request #1621
Opened 2022-03-23 16:14 UTC by rburema

The code as it was assumed that each junction specified the width for the _previous_ line it was connected to, but it actually specifies the width for the _next_ line it's connected to.

This caused an issue where it could make the symmetrical beadings so far out of kilter that it's easily visible in the preview.

Technically this still can happen, but only because the Maximum Extrusion Area Deviation is set to a very large value in the front-end, so the simplification doesn't really care about the weights. We should probably put it back to 2000 square micron, as it was.

2022-03-24 09:36 UTC, Ghostkeeper commented
Some of the ExtrusionLine tests are currently failing. We'll have to take a look at which is correct; the code or the tests.

2022-03-24 10:00 UTC, Ghostkeeper requested changes

2022-03-24 11:34 UTC, rburema commented on src/utils/ExtrusionLine.cpp
> +    const coord_t width_diff = llabs(B.w - A.w);
Ah I missed that. When I write things myself I already use that.

2022-03-24 11:51 UTC, rburema commented on src/utils/ExtrusionLine.cpp
>          return ab_length > bc_length ? width_diff * bc_length : width_diff * ab_length;
I don't think so; the result of the function is supposed to be the difference in area caused by the proposed merge. Which is the difference times the length of the one you _don't_ keep.

2022-03-24 12:22 UTC, rburema commented on src/utils/ExtrusionLine.cpp
> +        weighted_average_width = (ab_length * A.w + bc_length * B.w) / vSize(C - A);
That works better: We can even up the Maximal Area Deviation from 2000 to 5000 micron, and the result still looks correct on visual inspection :-)

2022-03-25 12:42 UTC, Ghostkeeper approved these changes
Looks much more logical this way. Nice!

2022-03-25 13:45 UTC, merged