Fix disconnected support due to support horizontal expansion
Ultimaker/CuraEngine pull request #1759
Opened 2022-11-02 15:25 UTC by rijkvanmanen

By checking of the model is splitting the support areas, this undesired behaviour can be easily identified. By expanding the model with the same amount as the horizontal expansion, it can be found which part(s) need to be removed.

CURA-9844

2022-11-08 14:07 UTC, smartavionics commented on src/support.cpp
> +                    i++;
Do you really want to increment i when you have just removed the the i'th element ?

2022-12-14 16:59 UTC, Joeydelarago requested changes

2022-12-14 16:59 UTC, Joeydelarago commented on src/support.cpp
> +            const int layer_size = layer_this.size();
You should give this a more descriptive name, it isn't clear a few lines down what the difference is between layer\_size and layer\_this.size()

2022-12-14 16:59 UTC, Joeydelarago commented on src/support.cpp
> +                for (PolygonsPart poly : layer_this.splitIntoParts())
This could also do with a more descriptive name. Something like layer\_part or support\_part

2022-12-21 15:46 UTC, rijkvanmanen commented
A different solution for the same problem is proposed in CURA-9996. I will come back to this PR after we finished the work for CURA-9996.

2023-01-16 14:05 UTC, rijkvanmanen commented
A better solution is now implemented with CURA-10152. So this PR will be closed

2023-01-16 14:05 UTC, closed without merging