CURA-10129-Improve-minimum-layer-time-for-dual-extrusion
Ultimaker/CuraEngine pull request #1796
Opened 2023-01-05 15:48 UTC by rijkvanmanen

Now the minimum layer time slow down is applied to the last extruder instead of to the last extruder plan. And the time spend on other extruder plans also taken into account.

2023-03-13 12:34 UTC, jellespijker requested changes
Made some suggestions how you can modernize the `for` loops that you use to determine the maximum extruder and calculate the time other extruder plans.

2023-03-13 12:34 UTC, jellespijker commented on src/LayerPlan.cpp
> +    }
```suggestion
    const size_t max_extruder_nr = ranges::max_element(extruder_plans, [](const ExtruderPlan& a, const ExtruderPlan& b) { return a.extruder_nr < b.extruder_nr; })->extruder_nr;
```

Don't forget to include max_element.hpp at the top
```
#include <range/v3/algorithm/max_element.hpp>
```

2023-03-13 12:34 UTC, jellespijker commented on src/LayerPlan.cpp
> +    }
```suggestion
    auto other_extr_plans = extruder_plans 
                          | ranges::views::filter([max_extruder_nr](const ExtruderPlan& extruder_plan) { return extruder_plan.extruder_nr != max_extruder_nr; })
                          | ranges::views::transform([starting_position](ExtruderPlan& extruder_plan) { return extruder_plan.computeNaiveTimeEstimates(starting_position).getTotalTime(); });
    const double time_other_extr_plans = ranges::accumulate(other_extr_plans, 0.0);
```

Don't forget to include at the top:
```
#include <range/v3/numeric/accumulate.hpp>
#include <range/v3/view/transform.hpp>
#include <range/v3/view/filter.hpp>
```

2023-03-13 16:29 UTC, rijkvanmanen commented on src/LayerPlan.cpp
> +    }
outdated

2023-03-14 16:37 UTC, jellespijker approved these changes
LGTM;
![image](https://user-images.githubusercontent.com/8535734/225075035-8fa3d829-3084-4aec-8b2e-d2a35c351d3d.png)

2023-03-14 16:41 UTC, jellespijker commented
Breaks with 3 or more extruders:
```
CuraEngine: /home/jspijker/cura_wp/CuraEngine/src/LayerPlanBuffer.cpp:416: void cura::LayerPlanBuffer::insertFinalPrintTempCommand(std::vector<cura::ExtruderPlan*>&, unsigned int): Assertion `(time_window >= 0 || last_extruder_plan.estimates.getMaterial() == 0) && "Time window should always be positive if we actually extrude"' failed.

```

2023-04-26 13:23 UTC, rburema commented
Just to be complete, I'll add it here too: 'Break with >3 extruders also happens in main in the same way, so it’s not connected to this PR.'

2023-04-26 13:24 UTC, merged