Add engine info handler for getting engine version and hash
Ultimaker/CuraEngine pull request #2146
Opened 2024-10-10 09:05 UTC by saumyaj3

Implemented a handler for the `--engine_info_cb` flag to handle engine information retrieval. Added functionality to create and send engine info messages, which include the Cura engine version and hash, to Emscripten. Updated CMake and conan files to pass Cura engine hash.

NP-349

2024-10-10 15:32 UTC, jellespijker requested changes
LGTM;

But you might want to base it and merge it to `5.9` instead of `main` also ask @wawanbreton or @rburema for a review

2024-10-14 06:59 UTC, wawanbreton commented
Do you need this in 5.9 ? If not, it is preferable to keep it in main.

2024-10-14 07:43 UTC, jellespijker commented
> Do you need this in 5.9 ? If not, it is preferable to keep it in main.

Neoprep will be based on 5.9, so yes we need it in the release branch. @saumyaj3 needs to base it from `5.9` it that scenario.

I don't think there will be any risk for Cura with merging it since the changes are in the Emscripten communication class, which will not be compiled for desktop applications

2024-10-14 08:00 UTC, saumyaj3 commented
I changed it to 5.9 branch

2024-10-14 08:07 UTC, wawanbreton approved these changes
Looks good

2024-10-14 08:12 UTC, jellespijker commented
@saumya did you also base it from 5.9? otherwise we will pull in main into 5.9

2024-10-14 08:20 UTC, saumyaj3 commented
I started working from main. The package created is also from main. I can also recreate the packages

2024-10-14 08:46 UTC, merged